name: Validation Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-validation:
    uses: ./.github/workflows/validate-core.yml
    secrets: inherit
